---
apiVersion: v2
description: "A community-supported supercharged version of paperless with an included ftp server: scan, index and archive all your physical documents."
name: paperless-ngx
type: application
home: https://github.com/CrystalNET-org/helm-paperless-ngx
icon: https://avatars.githubusercontent.com/u/99562962?s=48&v=4
version: 0.2.17
# renovate: image=paperlessngx/paperless-ngx
appVersion: "2.3.2"
kubeVersion: ">=1.22.0-0"
maintainers:
  - name: psych0d0g
    email: h@xx0r.eu
sources:
  - https://github.com/paperless-ngx/paperless-ngx
  - https://github.com/CrystalNET-org/helm-paperless-ngx
dependencies:
  - name: redis
    version: ~18.6.0
    repository: https://charts.bitnami.com/bitnami
    alias: redis
    condition: redis.enabled
  - name: mariadb
    version: ~15.0.0
    repository: https://charts.bitnami.com/bitnami
    alias: mariadb
    condition: mariadb.enabled
  - name: postgresql
    version: ~13.2.24
    repository: https://charts.bitnami.com/bitnami
    alias: postgresql
    condition: postgresql.enabled
