repos:
  - repo: https://github.com/norwoodj/helm-docs
    rev: v1.12.0
    hooks:
      - id: helm-docs
        args:
          - --chart-search-root=.
          - --template-files=../README.md.gotmpl
          - --output-file=../README.md