apiVersion: v1
kind: Service
metadata:
  name: {{ include "paperless.fullname" . }}
  labels:
    {{- include "paperless.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 8000
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "paperless.selectorLabels" . | nindent 4 }}
{{- if .Values.config.ftpd.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "paperless.fullname" . }}-ftp
  labels:
    {{- include "paperless.labels" . | nindent 4 }}
spec:
  type: {{ .Values.config.ftpd.service_type }}
  ports:
    - port: 21
      targetPort: ftp
      protocol: TCP
      name: ftp
    - port: 4559
      targetPort: pasv1
      protocol: TCP
      name: pasv1
    - port: 4560
      targetPort: pasv2
      protocol: TCP
      name: pasv2
    - port: 4561
      targetPort: pasv3
      protocol: TCP
      name: pasv3
    - port: 4562
      targetPort: pasv4
      protocol: TCP
      name: pasv4
    - port: 4563
      targetPort: pasv5
      protocol: TCP
      name: pasv5
    - port: 4564
      targetPort: pasv6
      protocol: TCP
      name: pasv6

  selector:
    {{- include "paperless.selectorLabels" . | nindent 4 }}
{{- end }}