depends_on:
  - helm-test

when:
  - event: tag
  - event: pull_request

steps:
  pack-chart:
    image: quay.io/helmpack/chart-releaser:v1.6.1
    commands:
      - mkdir -p .cr-index
      - cr package charts/woodpecker

  release-chart:
    image: quay.io/helmpack/chart-releaser:v1.6.1
    secrets:
      - source: github_token
        target: CR_TOKEN
    commands:
      - git config --global user.email "woodpecker-bot@crystalnet.org"
      - git config --global user.name "woodpecker-bot"
      - cr upload --skip-existing --owner woodpecker-ci --git-repo woodpecker-ci.github.io --release-name-template "helm-{{ .Name }}-{{ .Version }}"
      - git clone https://github.com/woodpecker-ci/woodpecker-ci.github.io.git
      - cd woodpecker-ci.github.io/
      - cr index --owner woodpecker-ci --git-repo woodpecker-ci.github.io --pages-branch main --package-path ../.cr-release-packages --index-path ../.cr-index/index.yaml --push --release-name-template "helm-{{ .Name }}-{{ .Version }}"
      - cd ..
      - rm -rf woodpecker-ci.github.io/
      - git reset --hard
    when:
      - event: tag
