depends_on:
  - helm-test

when:
  - event: tag
  - event: pull_request

steps:
  release-chart-to-harbor:
    image: harbor.crystalnet.org/dockerhub-proxy/alpine/helm:3.21.2
    environment:
      HELMREPO_USER:
        from_secret: harbor_helmrepo_user
      HELMREPO_PASSWORD:
        from_secret: harbor_helmrepo_password
    commands:
      - helm registry login -u $${HELMREPO_USER} -p $${HELMREPO_PASSWORD} harbor.crystalnet.org/charts
      - helm dependencies update chart
      - helm package chart
      - helm push *.tgz oci://harbor.crystalnet.org/charts
    when:
      - event: tag
