clone:
  git:
    image: harbor.crystalnet.org/dockerhub-proxy/woodpeckerci/plugin-git:2.4.0
    settings:
      partial: false
      depth: 1

steps:
  renovate:
    image: harbor.crystalnet.org/dockerhub-proxy/renovate/renovate:37.122.0
    secrets: 
      - github_com_token
      - renovate_token
    environment:
      - RENOVATE_CONFIG_FILE=.woodpecker/renovate_config.json
      - RENOVATE_DRY_RUN=false
      - RENOVATE_ENDPOINT=https://api.github.com
      - SHELL=/bin/bash
    commands:
      - LOG_LEVEL=debug renovate --ignore-pr-author true
when:
  - event: cron
    branch: ${CI_REPO_DEFAULT_BRANCH}
  - event: manual
    branch: ${CI_REPO_DEFAULT_BRANCH}